# Generated by Django 5.1.7 on 2025-03-22 16:38

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours', models.IntegerField()),
                ('total_miles', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.IntegerField()),
                ('fuel_stops', models.JSONField(default=list)),
                ('rest_stops', models.JSONField(default=list)),
                ('route_path', models.JSONField(default=list)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('off_duty_hours', models.FloatField()),
                ('sleeper_berth_hours', models.FloatField()),
                ('driving_hours', models.FloatField()),
                ('on_duty_hours', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.trip')),
            ],
        ),
    ]
